[book]
title = "Knowledge Repository"
authors = ["Rachel Brindle"]
description = "Rachel's Digital Garden"

[build]
preprocess = ["links", "index"]

[output.html]
curly-quotes = true
no-section-label = true
mathjax-support = true
additional-css = ["css/custom.css"]
git-repository-url = "https://github.com/younata/personal_knowledge/tree/main"
edit-url-template = "https://github.com/younata/personal_knowledge/edit/main/{path}"

[output.api]

[preprocessor.section-validator]
hide_invalid = false
invalid_message = "🚨 Warning, this content is out of date and is included for historical reasons."

[preprocessor.chapter-path]
after = ["section-validator"]
strict = true

[preprocessor.git-atom]
after = ["chapter-path"]
base_url = "https://knowledge.rachelbrindle.com"
article_preview_lines = 10
