[book]
title = "Knowledge Repository"
authors = ["Rachel Brindle"]
description = "Rachel's second brain"

[build]
preprocess = ["links", "index"]

[output.html]
curly-quotes = true
no-section-label = true
mathjax-support = true
additional-css = ["css/custom.css"]

[output.api]
