[book]
title = "Knowledge Repository"
authors = ["Rachel Brindle"]
description = "Rachel's second brain"

[build]
preprocess = ["links", "index"]

[output.html]
curly-quotes = true
no-section-label = true
mathjax-support = true
additional-css = ["css/custom.css"]
git-repository-url = "https://github.com/younata/personal_knowledge/tree/master"

[output.api]

[preprocessor.section-validator]
hide_invalid = false
invalid_message = "🚨 Warning, this content is out of date and is included for historical reasons."
